name: Format Python Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  format:
    name: Format Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ruff
        run: pip install ruff

      - name: Format Code
        run: ruff format .

      - name: Sort Imports and Fix
        run: ruff check . --fix

      - name: Check Changes
        run: git diff --exit-code